### ISSUE TITLE
Replace current dummy code/test with example of minimal Pytorch Tensor

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#13]
**Is your feature request related to a problem? Please describe.**
It would be interesting to have a more meaningful  source code example

**Describe the solution you'd like**
- [ ] Example in source code of a minimal Pytorch Tensor
- [ ] Unit test for example of a minimal Pytorch Tensor

**Comment by codeboy5** [comment]
Hi, I would like to take up this issue.
Can you give a little more description?

**Comment by Benardi** [comment]
The dummy implementation should be replaced with a minimalist/dummy implementation that somehow employs a Pytorch tensor. As it's a dummy implementation  **what it does is not that important**, only that it should a Pytorch tensor. 
This implementation should have at least one unit test

**Comment by codeboy5** [comment]
Solved in #20 PR. @Benardi please review it.
Sorry for the delay.
