### ISSUE TITLE
Add scipr-lab/libsnark to current project via git submodule

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#14]
**Is your feature request related to a problem? Please describe.**
In order to build and the wrap the scipr-lab/libsnark library it must be included in the project. However, its versioning should not be disregarded

**Describe the solution you'd like**
* Add https://github.com/scipr-lab/libsnark as a git submodule
* Provide commands to init/reset/update the submodule (via README.md)

**Comment by shaanrockz** [comment]
I wish to work on this
