### ISSUE TITLE
Add logic to compile the submodule libsnark

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#19]
**Is your feature request related to a problem? Please describe.**
To wrap the [libsnark](https://github.com/scipr-lab/libsnark/tree/477c9dfd07b280e42369f82f89c08416319e24ae) package  it's necessary to compile it. The compiled .so file can then be added to this project's wheel.

**Describe the solution you'd like**
Some routine / script that processes and compiles the libsnark into a .so (or similar) file

**Additional context**
- The [Openmined/PyDP](https://github.com/OpenMined/PyDP) project has done something similar

**Comment by shaanrockz** [comment]
I wish to do this.

**Comment by codeboy5** [comment]
Hey @shaanrockz are you working on this issue ?

**Comment by shaanrockz** [comment]
> Hey @shaanrockz are you working on this issue ?
> 
> 

Yes
