### ISSUE TITLE
Redundant CI Workflows

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#21]
**Describe the bug**
Current CI configuration produces a redundant workflow

**Expected behavior**
Only one of the two workflows shown below should exist

**Screenshots**
![image](https://user-images.githubusercontent.com/9937551/76988059-ee894700-6922-11ea-8961-44d5a6dac9f3.png)

**Comment by codeboy5** [comment]
I would like to take up this issue

**Comment by codeboy5** [comment]
@Benardi I think the Tests work can be just removed, with the functionality added in the CI workflow.
Does that sound okay ?

**Comment by codeboy5** [comment]
Solved in #22 PR. @Benardi please review it.
