### ISSUE TITLE
Incorporate lib build into CI 

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#28]
**Is your feature request related to a problem? Please describe.**
We should ensure that lib can build for each new version of this project

**Describe the solution you'd like**
A new testing environment for the library compilation in the existing CI

**Comment by codeboy5** [comment]
I would like to take this up

**Comment by shaanrockz** [comment]
I would like to take this up

**Comment by vineetjai** [comment]
I would also like to work on this.

**Comment by Benardi** [comment]
@vineetjai Sorry, first come first served. If @shaanrockz is willingly you might synchronize and work with him. You guys can find one another in the Slack channel. Nonetheless @shaanrockz  is the official assignee.

**Comment by shaanrockz** [comment]
Hey @Benardi, while building library in CI the cmake wants a specific version of boost (1.4) over the already installed version (1.69). Should I change the cmakelist of libsnark to get any newer version (which would be problematic after updating hte submodule) or should I amend the environment itself by installing the said version? (sudo activity is fine ?) 

![image](https://user-images.githubusercontent.com/11453667/77463291-aa57e400-6e05-11ea-8b08-3d21c8d21cd5.png)

**Comment by gargarchit** [comment]
This issue was partially resolved in #32 
I have created Issue #33 for next part.

**Comment by Benardi** [comment]
> This issue was partially resolved in #32
> I have created Issue #33 for next part.

As this has been moved to #33 I will close this issue
