### ISSUE TITLE
Add bindings to create a Python module from C++ compiled library

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#29]
**Is your feature request related to a problem? Please describe.**
The compiled C++ library should be provided as a Python module

**Comment by codeboy5** [comment]
I would like to work on this

**Comment by gargarchit** [comment]
I would also like to work on this, will make updates on @codeboy5 work.

**Comment by gargarchit** [comment]
Hi, @codeboy5 are you working on this issue else, I can try this.

**Comment by codeboy5** [comment]
Hi @gargarchit Yes I am working on this issue if you want to help/colab we can plan something.

**Comment by gargarchit** [comment]
Yeah we can do

**Comment by codeboy5** [comment]
Do you have any idea of python bindings?

**Comment by gargarchit** [comment]
Yeah, I have done python binding with  c++

**Comment by codeboy5** [comment]
I was planning to use pybind11.
Same as the PyDP library.

**Comment by gargarchit** [comment]
Okay, I will check this and try something with this

**Comment by Benardi** [comment]
@codeboy5 Any updates ?

**Comment by codeboy5** [comment]
@Benardi I was going through the PyDP library, I would add the bindings for some classes and push a PR soon.

**Comment by codeboy5** [comment]
Hi @Benardi , I have added the setup for pybind11 and tested it by wrapping some dummy code. 
Opened a PR #38 for the same.
Do you have in mind for which files should I add the binding first?
