### ISSUE TITLE
Incorporate lib build into CI for MacOS

### ISSUE THREAD

**Issue by gargarchit** [Benardi/PyZPK#33]
**Is your feature request related to a problem? Please describe.**
We should ensure that lib can build for each new version of this project while running in MacOS also

**Describe the solution you'd like**
A new testing environment for the library compilation in the existing CI

**Comment by vineetjai** [comment]
I would like to work on this.

**Comment by gargarchit** [comment]
@vineetjai did you worked on this issue.

**Comment by vineetjai** [comment]
@gargarchit  I am working on this issue. If you have anything maybe we can discuss it at slack.

**Comment by gargarchit** [comment]
Yeah, it's same like @shaanrocks done in #28 but for different OS. So, some commands will change but it will be mostly similar.
