### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by codeboy5** [Benardi/PyZPK#40]
**Is your feature request related to a problem? Please describe.**
As the setup involves a number of setups, adding docker support would allow new users to contribute, especially users using windows

**Describe the solution you'd like**
Adding A Dockerfile so that users can build a container with everything installed.

**Comment by codeboy5** [comment]
Hi @Benardi , I have added a Dockerfile along with instructions to run it. 
Please have a look.

**Comment by Benardi** [comment]
I like the initiative, but I can't see the benefit of Docker for this particular project.
This will be primarily a library, not an application and as such it will be provided via pip / Pypi.

**Comment by codeboy5** [comment]
It is primarily intended for someone who wants to contribute, for e.g. someone using windows or some who doesn't want to go through all the steps.

**Comment by Benardi** [comment]
This would only be true if an image were available via DockerHub

**Comment by codeboy5** [comment]
The idea being that someone would clone the repo and make the changes. Build the image and run it using the Dockerfile provided to test it.
Recently https://github.com/OpenMined/PyDP added a similar feature so I thought it might be a good addition.
Anyways I also get your point, should I close this issue?
